---
title: "Results_brain"
author: "Joshua Eigenmann"
date: '2022-07-01'
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Results

## Brain

Diagramof brain related genes

### 1. Ion channels

```{r setup, include=FALSE}
# ENST00000531293
data.ENST00000531293 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000531293")))
data.ENST00000531293 = data.ENST00000531293[,1:18]

week_4 =data.ENST00000531293[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000531293[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000531293[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000531293[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000531293[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000531293[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000531293 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000531293) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000531293,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000531293 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel")

# Summary
plot(data.ENST00000531293,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "red")
par(new=TRUE)
legend(1, 8.5, legend=c("ENST00000531293"),
       col=c("red"), lty=1, cex=0.8,title="Expressed genes")
```

[hier Texteinfügen]

### 2.Genes for neuronal development

```{r setup, include=FALSE}

# ENST00000602349
data.ENST00000602349 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000276646")))
data.ENST00000602349 = data.ENST00000602349[,1:18]

week_4 =data.ENST00000602349[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000602349[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000602349[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000602349[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000602349[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000602349[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000602349 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000602349) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000602349,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000602349 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel")

# ENST00000276646 & ENST00000529690
data.ENST00000276646 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000276646")))
data.ENST00000276646 = data.ENST00000276646[,1:18]

week_4 =data.ENST00000276646[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000276646[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000276646[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000276646[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000276646[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000276646[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000276646 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000276646) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000276646,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000276646 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel")

data.ENST00000529690 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000529690")))
data.ENST00000529690 = data.ENST00000529690[,1:18]

week_4 =data.ENST00000529690[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000529690[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000529690[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000529690[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000529690[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000529690[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000529690 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000529690) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000529690,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000529690 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel")

# ENST00000356660
data.ENST00000356660 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000356660")))
data.ENST00000356660 = data.ENST00000356660[,1:18]

week_4 =data.ENST00000356660[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000356660[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000356660[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000356660[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000356660[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000356660[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000356660 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000356660) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000356660,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000356660 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel")

# ENST00000518312 & ENST00000521485
data.ENST00000518312 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000518312")))
data.ENST00000518312 = data.ENST00000518312[,1:18]

week_4 =data.ENST00000518312[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000518312[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000518312[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000518312[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000518312[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000518312[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000518312 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000518312) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000518312,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000518312 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel")

data.ENST00000521485 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000521485")))
data.ENST00000521485 = data.ENST00000521485[,1:18]

week_4 =data.ENST00000521485[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000521485[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000521485[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000521485[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000521485[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000521485[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000521485 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000521485) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000521485,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000521485 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel")

# ENST00000577440
data.ENST00000577440 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000577440")))
data.ENST00000577440 = data.ENST00000577440[,1:18]

week_4 =data.ENST00000577440[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000577440[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000577440[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000577440[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000577440[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000577440[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000577440 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000577440) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000577440,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000577440 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel")

# ENST00000439476
data.ENST00000439476 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000439476")))
data.ENST00000439476 = data.ENST00000439476[,1:18]

week_4 =data.ENST00000439476[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000439476[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000439476[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000439476[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000439476[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000439476[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000439476 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000439476) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000439476,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000439476 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel")

# ENST00000539563
data.ENST00000539563 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000539563")))
data.ENST00000539563 = data.ENST00000539563[,1:18]

week_4 =data.ENST00000539563[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000539563[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000539563[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000539563[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000539563[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000539563[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000539563 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000539563) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000539563,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000539563 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel")

# Summary
plot(data.ENST00000602349,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "red", ylim = c(6.5,8.2))
par(new=TRUE)
plot(data.ENST00000276646,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "blue", ylim = c(6.5,8.2)) 
par(new=TRUE)
plot(data.ENST00000529690,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "orange", ylim = c(6.5,8.2))
par(new=TRUE)
plot(data.ENST00000356660,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "green", ylim =c(6.5,8.2))
par(new=TRUE)
plot(data.ENST00000518312,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "black", ylim = c(6.5,8.2))
par(new=TRUE)
plot(data.ENST00000521485,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "pink", ylim = c(6.5,8.2)) 
par(new=TRUE)
plot(data.ENST00000577440,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "purple", ylim = c(6.5,8.2))
par(new=TRUE)
plot(data.ENST00000439476,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "salmon", ylim = c(6.5,8.2))
par(new=TRUE)
plot(data.ENST00000539563,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "yellowgreen", ylim = c(6.5,8.2))
legend(1, 8.25, legend=c("ENST00000602349", "ENST00000276646", "ENST00000529690", "ENST00000356660", "ENST00000518312", "ENST00000521485", "ENST00000577440", "ENST00000439476", "ENST00000539563"),
       col=c("red", "blue", "orange", "green","black", "pink", "purple", "salmon", "yellowgreen"), lty=1, cex=0.8,title="Expressed genes")
```

[hier Texteinfügen]

### 3.Genes for cytokine

```{r setup, include=FALSE}
# ENST00000337225
data.ENST00000337225 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000337225")))
data.ENST00000337225 = data.ENST00000337225[,1:18]

week_4 =data.ENST00000337225[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000337225[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000337225[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000337225[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000337225[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000337225[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000337225 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000337225) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000337225,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000337225 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel")

# ENST00000579298
data.ENST00000579298 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000579298")))
data.ENST00000579298 = data.ENST00000579298[,1:18]

week_4 =data.ENST00000579298[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000579298[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000579298[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000579298[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000579298[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000579298[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000579298 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000579298) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000579298,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000579298 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel")

# ENST00000555247
data.ENST00000555247 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000555247")))
data.ENST00000555247 = data.ENST00000555247[,1:18]

week_4 =data.ENST00000555247[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000555247[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000555247[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000555247[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000555247[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000555247[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000555247 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000555247) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000555247,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000555247 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel")

# ENST00000590261
data.ENST00000590261 = as.data.frame(embryo_df_tissues %>%
                             filter(ensembl.transcript == str_extract(ENST, "ENST00000590261")))
data.ENST00000590261 = data.ENST00000590261[,1:18]

week_4 =data.ENST00000590261[1:3]
week_4 = apply(week_4,1,median)
week_5 =data.ENST00000590261[4:6]
week_5 = apply(week_5,1,median)
week_6 =data.ENST00000590261[7:9]
week_6 = apply(week_6,1,median)
week_7 =data.ENST00000590261[10:12]
week_7 = apply(week_7,1,median)
week_8 =data.ENST00000590261[13:15]
week_8 = apply(week_8,1,median)
week_9 =data.ENST00000590261[16:18]
week_9 = apply(week_9,1,median)

data.ENST00000590261 = c(week_4,week_5,week_6,week_7,week_8,week_9) 
names(data.ENST00000590261) = c(week_4,week_5,week_6,week_7,week_8,week_9)
plot(data.ENST00000590261,type = "b",lwd=1,pch=19, main = "Expression level of ENST00000590261 during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col)

# Summary
plot(data.ENST00000337225,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "red",ylim = c(7.6,9.7))
par(new=TRUE)
plot(data.ENST00000579298,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "blue",ylim = c(7.6,9.7)) 
par(new=TRUE)
plot(data.ENST00000555247,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "orange",ylim = c(7.6,9.7))
par(new=TRUE)
plot(data.ENST00000590261,type = "b",lwd=1,pch=19, main = "Geneexpression level during week 4 to 9", xlab = "weeks",ylab = "Expressionlevel",col = "green", ylim = c(7.6,9.7))
legend(1, 9.7, legend=c("ENST00000337225", "ENST00000579298", "ENST00000555247", "ENST00000590261"),
       col=c("red", "blue", "orange", "green"), lty=1, cex=0.8,title="Expressed genes")
```

[hier Texteinfügen]
