---
title: "test"
author: "Joshua Eigenmann"
date: "5/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

das ist ein test markdown

```{r}
x=rnorm(5000,mean=0,sd=1)
y=rnorm(5000,mean=5,sd=1)
plot(x,y)
```

```{r}
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(version = "3.15")

BiocManager::install(c("vsn", "affy", "AnnotationDbi"))
install.packages("limma")
install.packages("maps")
install.packages("mapproj")
install.packages("tidyverse")

library(affy)
library(vsn)
library(AnnotationDbi)
library(hgu133plus2hsenstcdf)
library(hgu133plus2hsenstprobe)
library(limma)
library(pheatmap)
library(tidyverse)
```

```{r}
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("vsn",force = TRUE)
library(vsn)
```

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.15")
```

```{r}
BiocManager::install("vsn",force = TRUE)
BiocManager::install("affy",force = TRUE)
BiocManager::install("AnnotationDbi",force = TRUE)
install.packages("limma",dependencies = TRUE)
install.packages("maps",dependencies = TRUE)
install.packages("mapproj",dependencies = TRUE)
install.packages("tidyverse",dependencies = TRUE)
library(affy)

#library(hgu133plus2hsenstcdf)
#library(hgu133plus2hsenstprobe)
library(limma)
library(pheatmap)

install.packages("broom", dependencies = TRUE)
library(broom)
library(tidyverse)
library(vsn)
library(AnnotationDbi)



install.packages("ggplot2")
library(ggplot2)
library(vsn)
```


